weather:
  api:
    key: ${API_KEY}
    units: metric

spring:
  application:
    name: weatheremotiontracker
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres/mydatabase
    username: myuser
    password: secret
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
