version: '3.8'
services:
  weather-feeling-tracker:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8060:8080'
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: weather_feeling_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
